// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web2.Data;

#nullable disable

namespace Web2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230919174211_migration19")]
    partial class migration19
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Web2.Models.Analyzes", b =>
                {
                    b.Property<int>("id_analysis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_analysis"));

                    b.Property<double>("calcium_excretion")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<double>("oxyproline_excretion")
                        .HasColumnType("double precision");

                    b.Property<double>("phosphorus_excretion")
                        .HasColumnType("double precision");

                    b.Property<double>("serum_calcium")
                        .HasColumnType("double precision");

                    b.Property<double>("serum_oxyproline")
                        .HasColumnType("double precision");

                    b.Property<double>("serum_phosphorus")
                        .HasColumnType("double precision");

                    b.Property<int>("severity_of_dst")
                        .HasColumnType("integer");

                    b.HasKey("id_analysis");

                    b.ToTable("analyzes");
                });

            modelBuilder.Entity("Web2.Models.Archive_Group", b =>
                {
                    b.Property<int>("id_patient")
                        .HasColumnType("integer");

                    b.Property<int>("id_group")
                        .HasColumnType("integer");

                    b.HasKey("id_patient", "id_group");

                    b.HasIndex("id_group");

                    b.ToTable("archive_group");
                });

            modelBuilder.Entity("Web2.Models.Examination", b =>
                {
                    b.Property<int>("id_examination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_examination"));

                    b.Property<bool>("change_in_the_contours_of_the_apophyses")
                        .HasColumnType("boolean");

                    b.Property<bool>("changing_the_contours_of_the_end_plates")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<bool>("decrease_in_the_height_of_the_intervertebral_disc")
                        .HasColumnType("boolean");

                    b.Property<bool>("enmg")
                        .HasColumnType("boolean");

                    b.Property<bool>("osteoporosis_of_the_vertebrae")
                        .HasColumnType("boolean");

                    b.Property<double>("posture_holding_time")
                        .HasColumnType("double precision");

                    b.Property<bool>("schmorl_hernia")
                        .HasColumnType("boolean");

                    b.Property<bool>("signs_of_osteochondrosis")
                        .HasColumnType("boolean");

                    b.Property<bool>("stabilographic_changes")
                        .HasColumnType("boolean");

                    b.Property<double>("the_amount_of_kyphosis_in_degress")
                        .HasColumnType("double precision");

                    b.Property<bool>("wedgeshaped_vertebral_bodies")
                        .HasColumnType("boolean");

                    b.HasKey("id_examination");

                    b.ToTable("examination");
                });

            modelBuilder.Entity("Web2.Models.Patient_Analyzes", b =>
                {
                    b.Property<int>("id_patient")
                        .HasColumnType("integer");

                    b.Property<int>("id_analysis")
                        .HasColumnType("integer");

                    b.HasKey("id_patient", "id_analysis");

                    b.HasIndex("id_analysis");

                    b.ToTable("patient_analyzes");
                });

            modelBuilder.Entity("Web2.Models.Patient_Examination", b =>
                {
                    b.Property<int>("id_patient")
                        .HasColumnType("integer");

                    b.Property<int>("id_examination")
                        .HasColumnType("integer");

                    b.HasKey("id_patient", "id_examination");

                    b.HasIndex("id_examination");

                    b.ToTable("patient_examinations");
                });

            modelBuilder.Entity("Web2.Models.User_Patients", b =>
                {
                    b.Property<string>("id_user")
                        .HasColumnType("text");

                    b.Property<int>("id_patient")
                        .HasColumnType("integer");

                    b.HasKey("id_user", "id_patient");

                    b.HasIndex("id_patient");

                    b.ToTable("user_patients");
                });

            modelBuilder.Entity("Web2.Models.patient_archive", b =>
                {
                    b.Property<int>("id_patient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_patient"));

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("patronymic")
                        .HasColumnType("text");

                    b.Property<string>("phone_num")
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id_patient");

                    b.ToTable("patient_archive");
                });

            modelBuilder.Entity("Web2.Models.patient_group", b =>
                {
                    b.Property<int>("id_group")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_group"));

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id_group");

                    b.ToTable("patient_groups");
                });

            modelBuilder.Entity("Web2.Models.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("Role");
                });

            modelBuilder.Entity("Web2.Models.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web2.Models.Archive_Group", b =>
                {
                    b.HasOne("Web2.Models.patient_group", "patient_group")
                        .WithMany()
                        .HasForeignKey("id_group")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web2.Models.patient_archive", "patient_archive")
                        .WithMany()
                        .HasForeignKey("id_patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient_archive");

                    b.Navigation("patient_group");
                });

            modelBuilder.Entity("Web2.Models.Patient_Analyzes", b =>
                {
                    b.HasOne("Web2.Models.Analyzes", "analyzes")
                        .WithMany()
                        .HasForeignKey("id_analysis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web2.Models.patient_archive", "patient_archive")
                        .WithMany()
                        .HasForeignKey("id_patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("analyzes");

                    b.Navigation("patient_archive");
                });

            modelBuilder.Entity("Web2.Models.Patient_Examination", b =>
                {
                    b.HasOne("Web2.Models.Examination", "examination")
                        .WithMany()
                        .HasForeignKey("id_examination")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web2.Models.patient_archive", "patient_archive")
                        .WithMany()
                        .HasForeignKey("id_patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("examination");

                    b.Navigation("patient_archive");
                });

            modelBuilder.Entity("Web2.Models.User_Patients", b =>
                {
                    b.HasOne("Web2.Models.patient_archive", "patient_archive")
                        .WithMany()
                        .HasForeignKey("id_patient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web2.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient_archive");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
